// Code generated by counterfeiter. DO NOT EDIT.
package vcsfakes

import (
	"sync"

	"github.com/geofffranks/herdle/internal/vcs"
)

type FakeTKRunner struct {
	AvailableStub        func() bool
	availableMutex       sync.RWMutex
	availableArgsForCall []struct {
	}
	availableReturns struct {
		result1 bool
	}
	availableReturnsOnCall map[int]struct {
		result1 bool
	}
	HasTicketsStub        func(string) (bool, error)
	hasTicketsMutex       sync.RWMutex
	hasTicketsArgsForCall []struct {
		arg1 string
	}
	hasTicketsReturns struct {
		result1 bool
		result2 error
	}
	hasTicketsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	ReadyStub        func(string) ([]string, error)
	readyMutex       sync.RWMutex
	readyArgsForCall []struct {
		arg1 string
	}
	readyReturns struct {
		result1 []string
		result2 error
	}
	readyReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	TicketsStub        func(string) ([]vcs.Ticket, error)
	ticketsMutex       sync.RWMutex
	ticketsArgsForCall []struct {
		arg1 string
	}
	ticketsReturns struct {
		result1 []vcs.Ticket
		result2 error
	}
	ticketsReturnsOnCall map[int]struct {
		result1 []vcs.Ticket
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTKRunner) Available() bool {
	fake.availableMutex.Lock()
	ret, specificReturn := fake.availableReturnsOnCall[len(fake.availableArgsForCall)]
	fake.availableArgsForCall = append(fake.availableArgsForCall, struct {
	}{})
	stub := fake.AvailableStub
	fakeReturns := fake.availableReturns
	fake.recordInvocation("Available", []interface{}{})
	fake.availableMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTKRunner) AvailableCallCount() int {
	fake.availableMutex.RLock()
	defer fake.availableMutex.RUnlock()
	return len(fake.availableArgsForCall)
}

func (fake *FakeTKRunner) AvailableCalls(stub func() bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = stub
}

func (fake *FakeTKRunner) AvailableReturns(result1 bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = nil
	fake.availableReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeTKRunner) AvailableReturnsOnCall(i int, result1 bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = nil
	if fake.availableReturnsOnCall == nil {
		fake.availableReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.availableReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeTKRunner) HasTickets(arg1 string) (bool, error) {
	fake.hasTicketsMutex.Lock()
	ret, specificReturn := fake.hasTicketsReturnsOnCall[len(fake.hasTicketsArgsForCall)]
	fake.hasTicketsArgsForCall = append(fake.hasTicketsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.HasTicketsStub
	fakeReturns := fake.hasTicketsReturns
	fake.recordInvocation("HasTickets", []interface{}{arg1})
	fake.hasTicketsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTKRunner) HasTicketsCallCount() int {
	fake.hasTicketsMutex.RLock()
	defer fake.hasTicketsMutex.RUnlock()
	return len(fake.hasTicketsArgsForCall)
}

func (fake *FakeTKRunner) HasTicketsCalls(stub func(string) (bool, error)) {
	fake.hasTicketsMutex.Lock()
	defer fake.hasTicketsMutex.Unlock()
	fake.HasTicketsStub = stub
}

func (fake *FakeTKRunner) HasTicketsArgsForCall(i int) string {
	fake.hasTicketsMutex.RLock()
	defer fake.hasTicketsMutex.RUnlock()
	argsForCall := fake.hasTicketsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTKRunner) HasTicketsReturns(result1 bool, result2 error) {
	fake.hasTicketsMutex.Lock()
	defer fake.hasTicketsMutex.Unlock()
	fake.HasTicketsStub = nil
	fake.hasTicketsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTKRunner) HasTicketsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasTicketsMutex.Lock()
	defer fake.hasTicketsMutex.Unlock()
	fake.HasTicketsStub = nil
	if fake.hasTicketsReturnsOnCall == nil {
		fake.hasTicketsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasTicketsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTKRunner) Ready(arg1 string) ([]string, error) {
	fake.readyMutex.Lock()
	ret, specificReturn := fake.readyReturnsOnCall[len(fake.readyArgsForCall)]
	fake.readyArgsForCall = append(fake.readyArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ReadyStub
	fakeReturns := fake.readyReturns
	fake.recordInvocation("Ready", []interface{}{arg1})
	fake.readyMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTKRunner) ReadyCallCount() int {
	fake.readyMutex.RLock()
	defer fake.readyMutex.RUnlock()
	return len(fake.readyArgsForCall)
}

func (fake *FakeTKRunner) ReadyCalls(stub func(string) ([]string, error)) {
	fake.readyMutex.Lock()
	defer fake.readyMutex.Unlock()
	fake.ReadyStub = stub
}

func (fake *FakeTKRunner) ReadyArgsForCall(i int) string {
	fake.readyMutex.RLock()
	defer fake.readyMutex.RUnlock()
	argsForCall := fake.readyArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTKRunner) ReadyReturns(result1 []string, result2 error) {
	fake.readyMutex.Lock()
	defer fake.readyMutex.Unlock()
	fake.ReadyStub = nil
	fake.readyReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeTKRunner) ReadyReturnsOnCall(i int, result1 []string, result2 error) {
	fake.readyMutex.Lock()
	defer fake.readyMutex.Unlock()
	fake.ReadyStub = nil
	if fake.readyReturnsOnCall == nil {
		fake.readyReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.readyReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeTKRunner) Tickets(arg1 string) ([]vcs.Ticket, error) {
	fake.ticketsMutex.Lock()
	ret, specificReturn := fake.ticketsReturnsOnCall[len(fake.ticketsArgsForCall)]
	fake.ticketsArgsForCall = append(fake.ticketsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TicketsStub
	fakeReturns := fake.ticketsReturns
	fake.recordInvocation("Tickets", []interface{}{arg1})
	fake.ticketsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTKRunner) TicketsCallCount() int {
	fake.ticketsMutex.RLock()
	defer fake.ticketsMutex.RUnlock()
	return len(fake.ticketsArgsForCall)
}

func (fake *FakeTKRunner) TicketsCalls(stub func(string) ([]vcs.Ticket, error)) {
	fake.ticketsMutex.Lock()
	defer fake.ticketsMutex.Unlock()
	fake.TicketsStub = stub
}

func (fake *FakeTKRunner) TicketsArgsForCall(i int) string {
	fake.ticketsMutex.RLock()
	defer fake.ticketsMutex.RUnlock()
	argsForCall := fake.ticketsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTKRunner) TicketsReturns(result1 []vcs.Ticket, result2 error) {
	fake.ticketsMutex.Lock()
	defer fake.ticketsMutex.Unlock()
	fake.TicketsStub = nil
	fake.ticketsReturns = struct {
		result1 []vcs.Ticket
		result2 error
	}{result1, result2}
}

func (fake *FakeTKRunner) TicketsReturnsOnCall(i int, result1 []vcs.Ticket, result2 error) {
	fake.ticketsMutex.Lock()
	defer fake.ticketsMutex.Unlock()
	fake.TicketsStub = nil
	if fake.ticketsReturnsOnCall == nil {
		fake.ticketsReturnsOnCall = make(map[int]struct {
			result1 []vcs.Ticket
			result2 error
		})
	}
	fake.ticketsReturnsOnCall[i] = struct {
		result1 []vcs.Ticket
		result2 error
	}{result1, result2}
}

func (fake *FakeTKRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTKRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vcs.TKRunner = new(FakeTKRunner)
