// Code generated by counterfeiter. DO NOT EDIT.
package vcsfakes

import (
	"sync"

	"github.com/geofffranks/herdle/internal/vcs"
)

type FakeGHRunner struct {
	PRListStub        func(string, string) ([]vcs.PR, error)
	pRListMutex       sync.RWMutex
	pRListArgsForCall []struct {
		arg1 string
		arg2 string
	}
	pRListReturns struct {
		result1 []vcs.PR
		result2 error
	}
	pRListReturnsOnCall map[int]struct {
		result1 []vcs.PR
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGHRunner) PRList(arg1 string, arg2 string) ([]vcs.PR, error) {
	fake.pRListMutex.Lock()
	ret, specificReturn := fake.pRListReturnsOnCall[len(fake.pRListArgsForCall)]
	fake.pRListArgsForCall = append(fake.pRListArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.PRListStub
	fakeReturns := fake.pRListReturns
	fake.recordInvocation("PRList", []interface{}{arg1, arg2})
	fake.pRListMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGHRunner) PRListCallCount() int {
	fake.pRListMutex.RLock()
	defer fake.pRListMutex.RUnlock()
	return len(fake.pRListArgsForCall)
}

func (fake *FakeGHRunner) PRListCalls(stub func(string, string) ([]vcs.PR, error)) {
	fake.pRListMutex.Lock()
	defer fake.pRListMutex.Unlock()
	fake.PRListStub = stub
}

func (fake *FakeGHRunner) PRListArgsForCall(i int) (string, string) {
	fake.pRListMutex.RLock()
	defer fake.pRListMutex.RUnlock()
	argsForCall := fake.pRListArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGHRunner) PRListReturns(result1 []vcs.PR, result2 error) {
	fake.pRListMutex.Lock()
	defer fake.pRListMutex.Unlock()
	fake.PRListStub = nil
	fake.pRListReturns = struct {
		result1 []vcs.PR
		result2 error
	}{result1, result2}
}

func (fake *FakeGHRunner) PRListReturnsOnCall(i int, result1 []vcs.PR, result2 error) {
	fake.pRListMutex.Lock()
	defer fake.pRListMutex.Unlock()
	fake.PRListStub = nil
	if fake.pRListReturnsOnCall == nil {
		fake.pRListReturnsOnCall = make(map[int]struct {
			result1 []vcs.PR
			result2 error
		})
	}
	fake.pRListReturnsOnCall[i] = struct {
		result1 []vcs.PR
		result2 error
	}{result1, result2}
}

func (fake *FakeGHRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGHRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vcs.GHRunner = new(FakeGHRunner)
