// Code generated by counterfeiter. DO NOT EDIT.
package vcsfakes

import (
	"sync"

	"github.com/geofffranks/herdle/internal/vcs"
)

type FakeGitRunner struct {
	AvailableStub        func() bool
	availableMutex       sync.RWMutex
	availableArgsForCall []struct {
	}
	availableReturns struct {
		result1 bool
	}
	availableReturnsOnCall map[int]struct {
		result1 bool
	}
	CurrentBranchStub        func(string) (string, error)
	currentBranchMutex       sync.RWMutex
	currentBranchArgsForCall []struct {
		arg1 string
	}
	currentBranchReturns struct {
		result1 string
		result2 error
	}
	currentBranchReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DivergenceStub        func(string, string, string) (int, int, error)
	divergenceMutex       sync.RWMutex
	divergenceArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	divergenceReturns struct {
		result1 int
		result2 int
		result3 error
	}
	divergenceReturnsOnCall map[int]struct {
		result1 int
		result2 int
		result3 error
	}
	FetchStub        func(string) error
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
		arg1 string
	}
	fetchReturns struct {
		result1 error
	}
	fetchReturnsOnCall map[int]struct {
		result1 error
	}
	IsDirtyStub        func(string) (bool, error)
	isDirtyMutex       sync.RWMutex
	isDirtyArgsForCall []struct {
		arg1 string
	}
	isDirtyReturns struct {
		result1 bool
		result2 error
	}
	isDirtyReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	LocalBranchExistsStub        func(string, string) (bool, error)
	localBranchExistsMutex       sync.RWMutex
	localBranchExistsArgsForCall []struct {
		arg1 string
		arg2 string
	}
	localBranchExistsReturns struct {
		result1 bool
		result2 error
	}
	localBranchExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	LocalBranchesStub        func(string) ([]vcs.Branch, error)
	localBranchesMutex       sync.RWMutex
	localBranchesArgsForCall []struct {
		arg1 string
	}
	localBranchesReturns struct {
		result1 []vcs.Branch
		result2 error
	}
	localBranchesReturnsOnCall map[int]struct {
		result1 []vcs.Branch
		result2 error
	}
	PruneRemoteStub        func(string, string) error
	pruneRemoteMutex       sync.RWMutex
	pruneRemoteArgsForCall []struct {
		arg1 string
		arg2 string
	}
	pruneRemoteReturns struct {
		result1 error
	}
	pruneRemoteReturnsOnCall map[int]struct {
		result1 error
	}
	RemoteBranchExistsStub        func(string, string, string) (bool, error)
	remoteBranchExistsMutex       sync.RWMutex
	remoteBranchExistsArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	remoteBranchExistsReturns struct {
		result1 bool
		result2 error
	}
	remoteBranchExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	RemoteBranchesStub        func(string, string) ([]string, error)
	remoteBranchesMutex       sync.RWMutex
	remoteBranchesArgsForCall []struct {
		arg1 string
		arg2 string
	}
	remoteBranchesReturns struct {
		result1 []string
		result2 error
	}
	remoteBranchesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	RemoteHeadStub        func(string, string) (string, error)
	remoteHeadMutex       sync.RWMutex
	remoteHeadArgsForCall []struct {
		arg1 string
		arg2 string
	}
	remoteHeadReturns struct {
		result1 string
		result2 error
	}
	remoteHeadReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	RemoteURLStub        func(string, string) (string, error)
	remoteURLMutex       sync.RWMutex
	remoteURLArgsForCall []struct {
		arg1 string
		arg2 string
	}
	remoteURLReturns struct {
		result1 string
		result2 error
	}
	remoteURLReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	RepoRootStub        func(string) (string, error)
	repoRootMutex       sync.RWMutex
	repoRootArgsForCall []struct {
		arg1 string
	}
	repoRootReturns struct {
		result1 string
		result2 error
	}
	repoRootReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitRunner) Available() bool {
	fake.availableMutex.Lock()
	ret, specificReturn := fake.availableReturnsOnCall[len(fake.availableArgsForCall)]
	fake.availableArgsForCall = append(fake.availableArgsForCall, struct {
	}{})
	stub := fake.AvailableStub
	fakeReturns := fake.availableReturns
	fake.recordInvocation("Available", []interface{}{})
	fake.availableMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitRunner) AvailableCallCount() int {
	fake.availableMutex.RLock()
	defer fake.availableMutex.RUnlock()
	return len(fake.availableArgsForCall)
}

func (fake *FakeGitRunner) AvailableCalls(stub func() bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = stub
}

func (fake *FakeGitRunner) AvailableReturns(result1 bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = nil
	fake.availableReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGitRunner) AvailableReturnsOnCall(i int, result1 bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = nil
	if fake.availableReturnsOnCall == nil {
		fake.availableReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.availableReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGitRunner) CurrentBranch(arg1 string) (string, error) {
	fake.currentBranchMutex.Lock()
	ret, specificReturn := fake.currentBranchReturnsOnCall[len(fake.currentBranchArgsForCall)]
	fake.currentBranchArgsForCall = append(fake.currentBranchArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CurrentBranchStub
	fakeReturns := fake.currentBranchReturns
	fake.recordInvocation("CurrentBranch", []interface{}{arg1})
	fake.currentBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) CurrentBranchCallCount() int {
	fake.currentBranchMutex.RLock()
	defer fake.currentBranchMutex.RUnlock()
	return len(fake.currentBranchArgsForCall)
}

func (fake *FakeGitRunner) CurrentBranchCalls(stub func(string) (string, error)) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = stub
}

func (fake *FakeGitRunner) CurrentBranchArgsForCall(i int) string {
	fake.currentBranchMutex.RLock()
	defer fake.currentBranchMutex.RUnlock()
	argsForCall := fake.currentBranchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitRunner) CurrentBranchReturns(result1 string, result2 error) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = nil
	fake.currentBranchReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) CurrentBranchReturnsOnCall(i int, result1 string, result2 error) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = nil
	if fake.currentBranchReturnsOnCall == nil {
		fake.currentBranchReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.currentBranchReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) Divergence(arg1 string, arg2 string, arg3 string) (int, int, error) {
	fake.divergenceMutex.Lock()
	ret, specificReturn := fake.divergenceReturnsOnCall[len(fake.divergenceArgsForCall)]
	fake.divergenceArgsForCall = append(fake.divergenceArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.DivergenceStub
	fakeReturns := fake.divergenceReturns
	fake.recordInvocation("Divergence", []interface{}{arg1, arg2, arg3})
	fake.divergenceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeGitRunner) DivergenceCallCount() int {
	fake.divergenceMutex.RLock()
	defer fake.divergenceMutex.RUnlock()
	return len(fake.divergenceArgsForCall)
}

func (fake *FakeGitRunner) DivergenceCalls(stub func(string, string, string) (int, int, error)) {
	fake.divergenceMutex.Lock()
	defer fake.divergenceMutex.Unlock()
	fake.DivergenceStub = stub
}

func (fake *FakeGitRunner) DivergenceArgsForCall(i int) (string, string, string) {
	fake.divergenceMutex.RLock()
	defer fake.divergenceMutex.RUnlock()
	argsForCall := fake.divergenceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGitRunner) DivergenceReturns(result1 int, result2 int, result3 error) {
	fake.divergenceMutex.Lock()
	defer fake.divergenceMutex.Unlock()
	fake.DivergenceStub = nil
	fake.divergenceReturns = struct {
		result1 int
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeGitRunner) DivergenceReturnsOnCall(i int, result1 int, result2 int, result3 error) {
	fake.divergenceMutex.Lock()
	defer fake.divergenceMutex.Unlock()
	fake.DivergenceStub = nil
	if fake.divergenceReturnsOnCall == nil {
		fake.divergenceReturnsOnCall = make(map[int]struct {
			result1 int
			result2 int
			result3 error
		})
	}
	fake.divergenceReturnsOnCall[i] = struct {
		result1 int
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeGitRunner) Fetch(arg1 string) error {
	fake.fetchMutex.Lock()
	ret, specificReturn := fake.fetchReturnsOnCall[len(fake.fetchArgsForCall)]
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.FetchStub
	fakeReturns := fake.fetchReturns
	fake.recordInvocation("Fetch", []interface{}{arg1})
	fake.fetchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitRunner) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *FakeGitRunner) FetchCalls(stub func(string) error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = stub
}

func (fake *FakeGitRunner) FetchArgsForCall(i int) string {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	argsForCall := fake.fetchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitRunner) FetchReturns(result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	fake.fetchReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitRunner) FetchReturnsOnCall(i int, result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	if fake.fetchReturnsOnCall == nil {
		fake.fetchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fetchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitRunner) IsDirty(arg1 string) (bool, error) {
	fake.isDirtyMutex.Lock()
	ret, specificReturn := fake.isDirtyReturnsOnCall[len(fake.isDirtyArgsForCall)]
	fake.isDirtyArgsForCall = append(fake.isDirtyArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsDirtyStub
	fakeReturns := fake.isDirtyReturns
	fake.recordInvocation("IsDirty", []interface{}{arg1})
	fake.isDirtyMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) IsDirtyCallCount() int {
	fake.isDirtyMutex.RLock()
	defer fake.isDirtyMutex.RUnlock()
	return len(fake.isDirtyArgsForCall)
}

func (fake *FakeGitRunner) IsDirtyCalls(stub func(string) (bool, error)) {
	fake.isDirtyMutex.Lock()
	defer fake.isDirtyMutex.Unlock()
	fake.IsDirtyStub = stub
}

func (fake *FakeGitRunner) IsDirtyArgsForCall(i int) string {
	fake.isDirtyMutex.RLock()
	defer fake.isDirtyMutex.RUnlock()
	argsForCall := fake.isDirtyArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitRunner) IsDirtyReturns(result1 bool, result2 error) {
	fake.isDirtyMutex.Lock()
	defer fake.isDirtyMutex.Unlock()
	fake.IsDirtyStub = nil
	fake.isDirtyReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) IsDirtyReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isDirtyMutex.Lock()
	defer fake.isDirtyMutex.Unlock()
	fake.IsDirtyStub = nil
	if fake.isDirtyReturnsOnCall == nil {
		fake.isDirtyReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isDirtyReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) LocalBranchExists(arg1 string, arg2 string) (bool, error) {
	fake.localBranchExistsMutex.Lock()
	ret, specificReturn := fake.localBranchExistsReturnsOnCall[len(fake.localBranchExistsArgsForCall)]
	fake.localBranchExistsArgsForCall = append(fake.localBranchExistsArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.LocalBranchExistsStub
	fakeReturns := fake.localBranchExistsReturns
	fake.recordInvocation("LocalBranchExists", []interface{}{arg1, arg2})
	fake.localBranchExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) LocalBranchExistsCallCount() int {
	fake.localBranchExistsMutex.RLock()
	defer fake.localBranchExistsMutex.RUnlock()
	return len(fake.localBranchExistsArgsForCall)
}

func (fake *FakeGitRunner) LocalBranchExistsCalls(stub func(string, string) (bool, error)) {
	fake.localBranchExistsMutex.Lock()
	defer fake.localBranchExistsMutex.Unlock()
	fake.LocalBranchExistsStub = stub
}

func (fake *FakeGitRunner) LocalBranchExistsArgsForCall(i int) (string, string) {
	fake.localBranchExistsMutex.RLock()
	defer fake.localBranchExistsMutex.RUnlock()
	argsForCall := fake.localBranchExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitRunner) LocalBranchExistsReturns(result1 bool, result2 error) {
	fake.localBranchExistsMutex.Lock()
	defer fake.localBranchExistsMutex.Unlock()
	fake.LocalBranchExistsStub = nil
	fake.localBranchExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) LocalBranchExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.localBranchExistsMutex.Lock()
	defer fake.localBranchExistsMutex.Unlock()
	fake.LocalBranchExistsStub = nil
	if fake.localBranchExistsReturnsOnCall == nil {
		fake.localBranchExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.localBranchExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) LocalBranches(arg1 string) ([]vcs.Branch, error) {
	fake.localBranchesMutex.Lock()
	ret, specificReturn := fake.localBranchesReturnsOnCall[len(fake.localBranchesArgsForCall)]
	fake.localBranchesArgsForCall = append(fake.localBranchesArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LocalBranchesStub
	fakeReturns := fake.localBranchesReturns
	fake.recordInvocation("LocalBranches", []interface{}{arg1})
	fake.localBranchesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) LocalBranchesCallCount() int {
	fake.localBranchesMutex.RLock()
	defer fake.localBranchesMutex.RUnlock()
	return len(fake.localBranchesArgsForCall)
}

func (fake *FakeGitRunner) LocalBranchesCalls(stub func(string) ([]vcs.Branch, error)) {
	fake.localBranchesMutex.Lock()
	defer fake.localBranchesMutex.Unlock()
	fake.LocalBranchesStub = stub
}

func (fake *FakeGitRunner) LocalBranchesArgsForCall(i int) string {
	fake.localBranchesMutex.RLock()
	defer fake.localBranchesMutex.RUnlock()
	argsForCall := fake.localBranchesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitRunner) LocalBranchesReturns(result1 []vcs.Branch, result2 error) {
	fake.localBranchesMutex.Lock()
	defer fake.localBranchesMutex.Unlock()
	fake.LocalBranchesStub = nil
	fake.localBranchesReturns = struct {
		result1 []vcs.Branch
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) LocalBranchesReturnsOnCall(i int, result1 []vcs.Branch, result2 error) {
	fake.localBranchesMutex.Lock()
	defer fake.localBranchesMutex.Unlock()
	fake.LocalBranchesStub = nil
	if fake.localBranchesReturnsOnCall == nil {
		fake.localBranchesReturnsOnCall = make(map[int]struct {
			result1 []vcs.Branch
			result2 error
		})
	}
	fake.localBranchesReturnsOnCall[i] = struct {
		result1 []vcs.Branch
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) PruneRemote(arg1 string, arg2 string) error {
	fake.pruneRemoteMutex.Lock()
	ret, specificReturn := fake.pruneRemoteReturnsOnCall[len(fake.pruneRemoteArgsForCall)]
	fake.pruneRemoteArgsForCall = append(fake.pruneRemoteArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.PruneRemoteStub
	fakeReturns := fake.pruneRemoteReturns
	fake.recordInvocation("PruneRemote", []interface{}{arg1, arg2})
	fake.pruneRemoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitRunner) PruneRemoteCallCount() int {
	fake.pruneRemoteMutex.RLock()
	defer fake.pruneRemoteMutex.RUnlock()
	return len(fake.pruneRemoteArgsForCall)
}

func (fake *FakeGitRunner) PruneRemoteCalls(stub func(string, string) error) {
	fake.pruneRemoteMutex.Lock()
	defer fake.pruneRemoteMutex.Unlock()
	fake.PruneRemoteStub = stub
}

func (fake *FakeGitRunner) PruneRemoteArgsForCall(i int) (string, string) {
	fake.pruneRemoteMutex.RLock()
	defer fake.pruneRemoteMutex.RUnlock()
	argsForCall := fake.pruneRemoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitRunner) PruneRemoteReturns(result1 error) {
	fake.pruneRemoteMutex.Lock()
	defer fake.pruneRemoteMutex.Unlock()
	fake.PruneRemoteStub = nil
	fake.pruneRemoteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitRunner) PruneRemoteReturnsOnCall(i int, result1 error) {
	fake.pruneRemoteMutex.Lock()
	defer fake.pruneRemoteMutex.Unlock()
	fake.PruneRemoteStub = nil
	if fake.pruneRemoteReturnsOnCall == nil {
		fake.pruneRemoteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pruneRemoteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitRunner) RemoteBranchExists(arg1 string, arg2 string, arg3 string) (bool, error) {
	fake.remoteBranchExistsMutex.Lock()
	ret, specificReturn := fake.remoteBranchExistsReturnsOnCall[len(fake.remoteBranchExistsArgsForCall)]
	fake.remoteBranchExistsArgsForCall = append(fake.remoteBranchExistsArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.RemoteBranchExistsStub
	fakeReturns := fake.remoteBranchExistsReturns
	fake.recordInvocation("RemoteBranchExists", []interface{}{arg1, arg2, arg3})
	fake.remoteBranchExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) RemoteBranchExistsCallCount() int {
	fake.remoteBranchExistsMutex.RLock()
	defer fake.remoteBranchExistsMutex.RUnlock()
	return len(fake.remoteBranchExistsArgsForCall)
}

func (fake *FakeGitRunner) RemoteBranchExistsCalls(stub func(string, string, string) (bool, error)) {
	fake.remoteBranchExistsMutex.Lock()
	defer fake.remoteBranchExistsMutex.Unlock()
	fake.RemoteBranchExistsStub = stub
}

func (fake *FakeGitRunner) RemoteBranchExistsArgsForCall(i int) (string, string, string) {
	fake.remoteBranchExistsMutex.RLock()
	defer fake.remoteBranchExistsMutex.RUnlock()
	argsForCall := fake.remoteBranchExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGitRunner) RemoteBranchExistsReturns(result1 bool, result2 error) {
	fake.remoteBranchExistsMutex.Lock()
	defer fake.remoteBranchExistsMutex.Unlock()
	fake.RemoteBranchExistsStub = nil
	fake.remoteBranchExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RemoteBranchExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.remoteBranchExistsMutex.Lock()
	defer fake.remoteBranchExistsMutex.Unlock()
	fake.RemoteBranchExistsStub = nil
	if fake.remoteBranchExistsReturnsOnCall == nil {
		fake.remoteBranchExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.remoteBranchExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RemoteBranches(arg1 string, arg2 string) ([]string, error) {
	fake.remoteBranchesMutex.Lock()
	ret, specificReturn := fake.remoteBranchesReturnsOnCall[len(fake.remoteBranchesArgsForCall)]
	fake.remoteBranchesArgsForCall = append(fake.remoteBranchesArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.RemoteBranchesStub
	fakeReturns := fake.remoteBranchesReturns
	fake.recordInvocation("RemoteBranches", []interface{}{arg1, arg2})
	fake.remoteBranchesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) RemoteBranchesCallCount() int {
	fake.remoteBranchesMutex.RLock()
	defer fake.remoteBranchesMutex.RUnlock()
	return len(fake.remoteBranchesArgsForCall)
}

func (fake *FakeGitRunner) RemoteBranchesCalls(stub func(string, string) ([]string, error)) {
	fake.remoteBranchesMutex.Lock()
	defer fake.remoteBranchesMutex.Unlock()
	fake.RemoteBranchesStub = stub
}

func (fake *FakeGitRunner) RemoteBranchesArgsForCall(i int) (string, string) {
	fake.remoteBranchesMutex.RLock()
	defer fake.remoteBranchesMutex.RUnlock()
	argsForCall := fake.remoteBranchesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitRunner) RemoteBranchesReturns(result1 []string, result2 error) {
	fake.remoteBranchesMutex.Lock()
	defer fake.remoteBranchesMutex.Unlock()
	fake.RemoteBranchesStub = nil
	fake.remoteBranchesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RemoteBranchesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.remoteBranchesMutex.Lock()
	defer fake.remoteBranchesMutex.Unlock()
	fake.RemoteBranchesStub = nil
	if fake.remoteBranchesReturnsOnCall == nil {
		fake.remoteBranchesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.remoteBranchesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RemoteHead(arg1 string, arg2 string) (string, error) {
	fake.remoteHeadMutex.Lock()
	ret, specificReturn := fake.remoteHeadReturnsOnCall[len(fake.remoteHeadArgsForCall)]
	fake.remoteHeadArgsForCall = append(fake.remoteHeadArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.RemoteHeadStub
	fakeReturns := fake.remoteHeadReturns
	fake.recordInvocation("RemoteHead", []interface{}{arg1, arg2})
	fake.remoteHeadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) RemoteHeadCallCount() int {
	fake.remoteHeadMutex.RLock()
	defer fake.remoteHeadMutex.RUnlock()
	return len(fake.remoteHeadArgsForCall)
}

func (fake *FakeGitRunner) RemoteHeadCalls(stub func(string, string) (string, error)) {
	fake.remoteHeadMutex.Lock()
	defer fake.remoteHeadMutex.Unlock()
	fake.RemoteHeadStub = stub
}

func (fake *FakeGitRunner) RemoteHeadArgsForCall(i int) (string, string) {
	fake.remoteHeadMutex.RLock()
	defer fake.remoteHeadMutex.RUnlock()
	argsForCall := fake.remoteHeadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitRunner) RemoteHeadReturns(result1 string, result2 error) {
	fake.remoteHeadMutex.Lock()
	defer fake.remoteHeadMutex.Unlock()
	fake.RemoteHeadStub = nil
	fake.remoteHeadReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RemoteHeadReturnsOnCall(i int, result1 string, result2 error) {
	fake.remoteHeadMutex.Lock()
	defer fake.remoteHeadMutex.Unlock()
	fake.RemoteHeadStub = nil
	if fake.remoteHeadReturnsOnCall == nil {
		fake.remoteHeadReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.remoteHeadReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RemoteURL(arg1 string, arg2 string) (string, error) {
	fake.remoteURLMutex.Lock()
	ret, specificReturn := fake.remoteURLReturnsOnCall[len(fake.remoteURLArgsForCall)]
	fake.remoteURLArgsForCall = append(fake.remoteURLArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.RemoteURLStub
	fakeReturns := fake.remoteURLReturns
	fake.recordInvocation("RemoteURL", []interface{}{arg1, arg2})
	fake.remoteURLMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) RemoteURLCallCount() int {
	fake.remoteURLMutex.RLock()
	defer fake.remoteURLMutex.RUnlock()
	return len(fake.remoteURLArgsForCall)
}

func (fake *FakeGitRunner) RemoteURLCalls(stub func(string, string) (string, error)) {
	fake.remoteURLMutex.Lock()
	defer fake.remoteURLMutex.Unlock()
	fake.RemoteURLStub = stub
}

func (fake *FakeGitRunner) RemoteURLArgsForCall(i int) (string, string) {
	fake.remoteURLMutex.RLock()
	defer fake.remoteURLMutex.RUnlock()
	argsForCall := fake.remoteURLArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitRunner) RemoteURLReturns(result1 string, result2 error) {
	fake.remoteURLMutex.Lock()
	defer fake.remoteURLMutex.Unlock()
	fake.RemoteURLStub = nil
	fake.remoteURLReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RemoteURLReturnsOnCall(i int, result1 string, result2 error) {
	fake.remoteURLMutex.Lock()
	defer fake.remoteURLMutex.Unlock()
	fake.RemoteURLStub = nil
	if fake.remoteURLReturnsOnCall == nil {
		fake.remoteURLReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.remoteURLReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RepoRoot(arg1 string) (string, error) {
	fake.repoRootMutex.Lock()
	ret, specificReturn := fake.repoRootReturnsOnCall[len(fake.repoRootArgsForCall)]
	fake.repoRootArgsForCall = append(fake.repoRootArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RepoRootStub
	fakeReturns := fake.repoRootReturns
	fake.recordInvocation("RepoRoot", []interface{}{arg1})
	fake.repoRootMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRunner) RepoRootCallCount() int {
	fake.repoRootMutex.RLock()
	defer fake.repoRootMutex.RUnlock()
	return len(fake.repoRootArgsForCall)
}

func (fake *FakeGitRunner) RepoRootCalls(stub func(string) (string, error)) {
	fake.repoRootMutex.Lock()
	defer fake.repoRootMutex.Unlock()
	fake.RepoRootStub = stub
}

func (fake *FakeGitRunner) RepoRootArgsForCall(i int) string {
	fake.repoRootMutex.RLock()
	defer fake.repoRootMutex.RUnlock()
	argsForCall := fake.repoRootArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitRunner) RepoRootReturns(result1 string, result2 error) {
	fake.repoRootMutex.Lock()
	defer fake.repoRootMutex.Unlock()
	fake.RepoRootStub = nil
	fake.repoRootReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) RepoRootReturnsOnCall(i int, result1 string, result2 error) {
	fake.repoRootMutex.Lock()
	defer fake.repoRootMutex.Unlock()
	fake.RepoRootStub = nil
	if fake.repoRootReturnsOnCall == nil {
		fake.repoRootReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.repoRootReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vcs.GitRunner = new(FakeGitRunner)
