// Code generated by counterfeiter. DO NOT EDIT.
package vcsfakes

import (
	"sync"

	"github.com/geofffranks/herdle/internal/vcs"
)

type FakeGHRunner struct {
	AuthenticatedStub        func() bool
	authenticatedMutex       sync.RWMutex
	authenticatedArgsForCall []struct {
	}
	authenticatedReturns struct {
		result1 bool
	}
	authenticatedReturnsOnCall map[int]struct {
		result1 bool
	}
	AvailableStub        func() bool
	availableMutex       sync.RWMutex
	availableArgsForCall []struct {
	}
	availableReturns struct {
		result1 bool
	}
	availableReturnsOnCall map[int]struct {
		result1 bool
	}
	KnownHostsStub        func() []string
	knownHostsMutex       sync.RWMutex
	knownHostsArgsForCall []struct {
	}
	knownHostsReturns struct {
		result1 []string
	}
	knownHostsReturnsOnCall map[int]struct {
		result1 []string
	}
	PRListStub        func(string, string) ([]vcs.PR, error)
	pRListMutex       sync.RWMutex
	pRListArgsForCall []struct {
		arg1 string
		arg2 string
	}
	pRListReturns struct {
		result1 []vcs.PR
		result2 error
	}
	pRListReturnsOnCall map[int]struct {
		result1 []vcs.PR
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGHRunner) Authenticated() bool {
	fake.authenticatedMutex.Lock()
	ret, specificReturn := fake.authenticatedReturnsOnCall[len(fake.authenticatedArgsForCall)]
	fake.authenticatedArgsForCall = append(fake.authenticatedArgsForCall, struct {
	}{})
	stub := fake.AuthenticatedStub
	fakeReturns := fake.authenticatedReturns
	fake.recordInvocation("Authenticated", []interface{}{})
	fake.authenticatedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGHRunner) AuthenticatedCallCount() int {
	fake.authenticatedMutex.RLock()
	defer fake.authenticatedMutex.RUnlock()
	return len(fake.authenticatedArgsForCall)
}

func (fake *FakeGHRunner) AuthenticatedCalls(stub func() bool) {
	fake.authenticatedMutex.Lock()
	defer fake.authenticatedMutex.Unlock()
	fake.AuthenticatedStub = stub
}

func (fake *FakeGHRunner) AuthenticatedReturns(result1 bool) {
	fake.authenticatedMutex.Lock()
	defer fake.authenticatedMutex.Unlock()
	fake.AuthenticatedStub = nil
	fake.authenticatedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGHRunner) AuthenticatedReturnsOnCall(i int, result1 bool) {
	fake.authenticatedMutex.Lock()
	defer fake.authenticatedMutex.Unlock()
	fake.AuthenticatedStub = nil
	if fake.authenticatedReturnsOnCall == nil {
		fake.authenticatedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.authenticatedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGHRunner) Available() bool {
	fake.availableMutex.Lock()
	ret, specificReturn := fake.availableReturnsOnCall[len(fake.availableArgsForCall)]
	fake.availableArgsForCall = append(fake.availableArgsForCall, struct {
	}{})
	stub := fake.AvailableStub
	fakeReturns := fake.availableReturns
	fake.recordInvocation("Available", []interface{}{})
	fake.availableMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGHRunner) AvailableCallCount() int {
	fake.availableMutex.RLock()
	defer fake.availableMutex.RUnlock()
	return len(fake.availableArgsForCall)
}

func (fake *FakeGHRunner) AvailableCalls(stub func() bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = stub
}

func (fake *FakeGHRunner) AvailableReturns(result1 bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = nil
	fake.availableReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGHRunner) AvailableReturnsOnCall(i int, result1 bool) {
	fake.availableMutex.Lock()
	defer fake.availableMutex.Unlock()
	fake.AvailableStub = nil
	if fake.availableReturnsOnCall == nil {
		fake.availableReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.availableReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGHRunner) KnownHosts() []string {
	fake.knownHostsMutex.Lock()
	ret, specificReturn := fake.knownHostsReturnsOnCall[len(fake.knownHostsArgsForCall)]
	fake.knownHostsArgsForCall = append(fake.knownHostsArgsForCall, struct {
	}{})
	stub := fake.KnownHostsStub
	fakeReturns := fake.knownHostsReturns
	fake.recordInvocation("KnownHosts", []interface{}{})
	fake.knownHostsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGHRunner) KnownHostsCallCount() int {
	fake.knownHostsMutex.RLock()
	defer fake.knownHostsMutex.RUnlock()
	return len(fake.knownHostsArgsForCall)
}

func (fake *FakeGHRunner) KnownHostsCalls(stub func() []string) {
	fake.knownHostsMutex.Lock()
	defer fake.knownHostsMutex.Unlock()
	fake.KnownHostsStub = stub
}

func (fake *FakeGHRunner) KnownHostsReturns(result1 []string) {
	fake.knownHostsMutex.Lock()
	defer fake.knownHostsMutex.Unlock()
	fake.KnownHostsStub = nil
	fake.knownHostsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeGHRunner) KnownHostsReturnsOnCall(i int, result1 []string) {
	fake.knownHostsMutex.Lock()
	defer fake.knownHostsMutex.Unlock()
	fake.KnownHostsStub = nil
	if fake.knownHostsReturnsOnCall == nil {
		fake.knownHostsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.knownHostsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeGHRunner) PRList(arg1 string, arg2 string) ([]vcs.PR, error) {
	fake.pRListMutex.Lock()
	ret, specificReturn := fake.pRListReturnsOnCall[len(fake.pRListArgsForCall)]
	fake.pRListArgsForCall = append(fake.pRListArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.PRListStub
	fakeReturns := fake.pRListReturns
	fake.recordInvocation("PRList", []interface{}{arg1, arg2})
	fake.pRListMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGHRunner) PRListCallCount() int {
	fake.pRListMutex.RLock()
	defer fake.pRListMutex.RUnlock()
	return len(fake.pRListArgsForCall)
}

func (fake *FakeGHRunner) PRListCalls(stub func(string, string) ([]vcs.PR, error)) {
	fake.pRListMutex.Lock()
	defer fake.pRListMutex.Unlock()
	fake.PRListStub = stub
}

func (fake *FakeGHRunner) PRListArgsForCall(i int) (string, string) {
	fake.pRListMutex.RLock()
	defer fake.pRListMutex.RUnlock()
	argsForCall := fake.pRListArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGHRunner) PRListReturns(result1 []vcs.PR, result2 error) {
	fake.pRListMutex.Lock()
	defer fake.pRListMutex.Unlock()
	fake.PRListStub = nil
	fake.pRListReturns = struct {
		result1 []vcs.PR
		result2 error
	}{result1, result2}
}

func (fake *FakeGHRunner) PRListReturnsOnCall(i int, result1 []vcs.PR, result2 error) {
	fake.pRListMutex.Lock()
	defer fake.pRListMutex.Unlock()
	fake.PRListStub = nil
	if fake.pRListReturnsOnCall == nil {
		fake.pRListReturnsOnCall = make(map[int]struct {
			result1 []vcs.PR
			result2 error
		})
	}
	fake.pRListReturnsOnCall[i] = struct {
		result1 []vcs.PR
		result2 error
	}{result1, result2}
}

func (fake *FakeGHRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGHRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vcs.GHRunner = new(FakeGHRunner)
